### Listar clientes
GET https://localhost:5001/api/pizza/listar

### Cadastrar cliente
POST https://localhost:5001/api/pizza/cadastrar
Content-Type: application/json

{
    "sabor": "requeijao",
    "tamanho" : "pequena"
    
}

### Buscar um cliente por CPF
GET https://localhost:5001/api/pizza/buscar/frango

### Deletar um cliente pelo ID
DELETE https://localhost:5001/api/pizza/deletar/1

### Alterar um cliente
PATCH  https://localhost:5001/api/pizza/alterar
Content-Type: application/json

{
    "id" : 1,
    "nome" : "Marcelo modificado",
    "telefone" : "42853424893",
    "cpf" : "9087654321"
}