### Listar clientes
GET https://localhost:5001/api/cliente/listar

### Cadastrar cliente
POST https://localhost:5001/api/cliente/cadastrar
Content-Type: application/json

{
    "nome" : "Marcelo Pacheco",
    "telefone" : "41984960234",
    "cpf" : "1234567890"
}

### Buscar um cliente por CPF
GET https://localhost:5001/api/cliente/buscar/1234567890

### Deletar um cliente pelo ID
DELETE https://localhost:5001/api/cliente/deletar/1

### Alterar um cliente
PATCH  https://localhost:5001/api/cliente/alterar
Content-Type: application/json

{
    "id" : 1,
    "nome" : "Marcelo modificado",
    "telefone" : "42853424893",
    "cpf" : "9087654321"
}